version: '3.5'

services:
  # PHP fpm
  application-backend:
    build: .
    restart: always
    tty: true
    working_dir: /var/www/application
    env_file:
      - .env
    volumes:
      - .:/var/www/application
    container_name: application-backend
    networks:
      net:
        ipv4_address: 172.21.0.2

  # Nginx Service
  application-nginx:
    image: nginx:alpine
    container_name: application-nginx
    networks:
      net:
        ipv4_address: 172.21.0.3
    restart: always
    tty: true
    environment:
      - "APPLICATION_UPSTREAM=application-backend:9000"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/templates/:/etc/nginx/templates/
      - ./public/:/var/www/application/public/
    ports:
      - "80:80"
      - "443:443"

  # MySQL Service
  application-mysql:
    image: library/mysql:8.0
    container_name: application-mysql
    networks:
      net:
        ipv4_address: 172.21.0.4
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: 3034
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
    volumes:
      - applicationMysqlData:/var/lib/mysql
      - applicationMysqlFiles:/var/lib/mysql-files

  # Queue Service
  application-beanstalkd:
    image: schickling/beanstalkd:latest
    container_name: application-beanstalkd
    networks:
      net:
        ipv4_address: 172.21.0.5
    ports:
      - "11300:11300"

#Docker Volumes
volumes:
  applicationMysqlData:
    driver: local
  applicationMysqlFiles:
    driver: local

#Docker Networks
networks:
  net:
    ipam:
      config:
        - subnet: 172.21.0.0/16